import type { ComponentType } from 'react';
import { Users, CalendarDays, ClipboardList, GraduationCap, UserRound, Megaphone, PartyPopper, BookOpen, ShieldAlert, Building2 } from 'lucide-react';

export type Field = { name: string; label: string; type?: string; required?: boolean; options?: string[]; span?: boolean };
export type ResourceConfig = { key: string; label: string; singular: string; icon: ComponentType<{ size?: number }>; columns: Array<[string,string]>; fields: Field[] };
const scope: Field[] = [{ name:'department',label:'Department',required:true },{ name:'semester',label:'Semester',type:'number',required:true }];

export const resources: ResourceConfig[] = [
  { key:'students',label:'Students',singular:'Student',icon:Users,columns:[['student_id','Student ID'],['full_name','Name'],['roll_number','Roll no.'],['department','Department'],['course','Course'],['semester','Sem.'],['whatsapp_number','WhatsApp']],fields:[{name:'student_id',label:'Student ID',required:true},{name:'full_name',label:'Full name',required:true},{name:'whatsapp_number',label:'WhatsApp number',required:true},{name:'roll_number',label:'Roll number',type:'number',required:true},{name:'department',label:'Department',required:true},{name:'course',label:'Course',required:true},{name:'semester',label:'Semester',type:'number',required:true}]},
  { key:'timetables',label:'Timetable',singular:'Class',icon:CalendarDays,columns:[['day_of_week','Day'],['start_time','Start'],['end_time','End'],['subject','Subject'],['room','Room'],['department','Class']],fields:[...scope,{name:'section',label:'Section',required:true},{name:'day_of_week',label:'Day',type:'select',options:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],required:true},{name:'start_time',label:'Start time',type:'time',required:true},{name:'end_time',label:'End time',type:'time',required:true},{name:'subject',label:'Subject',required:true},{name:'room',label:'Room'}]},
  { key:'assignments',label:'Assignments',singular:'Assignment',icon:ClipboardList,columns:[['title','Title'],['subject','Subject'],['department','Class'],['due_at','Due'],['max_marks','Marks']],fields:[{name:'title',label:'Title',required:true},{name:'subject',label:'Subject',required:true},...scope,{name:'section',label:'Section'},{name:'due_at',label:'Due date & time',type:'datetime-local',required:true},{name:'max_marks',label:'Maximum marks',type:'number'},{name:'description',label:'Instructions',type:'textarea',span:true},{name:'submission_url',label:'Submission link',type:'url',span:true}]},
  { key:'exams',label:'Exams',singular:'Exam',icon:GraduationCap,columns:[['title','Exam'],['subject','Subject'],['exam_date','Date'],['start_time','Start'],['room','Room']],fields:[{name:'title',label:'Exam title',required:true},{name:'subject',label:'Subject',required:true},...scope,{name:'exam_date',label:'Date',type:'date',required:true},{name:'start_time',label:'Start time',type:'time',required:true},{name:'end_time',label:'End time',type:'time',required:true},{name:'room',label:'Room'},{name:'instructions',label:'Instructions',type:'textarea',span:true}]},
  { key:'faculty',label:'Faculty',singular:'Faculty member',icon:UserRound,columns:[['full_name','Name'],['designation','Designation'],['department','Department'],['email','Email'],['phone','Phone']],fields:[{name:'full_name',label:'Full name',required:true},{name:'designation',label:'Designation',required:true},{name:'department',label:'Department',required:true},{name:'email',label:'Email',type:'email'},{name:'phone',label:'Phone'},{name:'office',label:'Office'},{name:'office_hours',label:'Office hours'},{name:'active',label:'Active',type:'checkbox'}]},
  { key:'notices',label:'Notices',singular:'Notice',icon:Megaphone,columns:[['title','Title'],['category','Category'],['priority','Priority'],['published_at','Published'],['expires_at','Expires']],fields:[{name:'title',label:'Title',required:true},{name:'category',label:'Category',type:'select',options:['general','academic','placement','internship','holiday','emergency'],required:true},{name:'priority',label:'Priority',type:'select',options:['low','normal','high','urgent']},{name:'department',label:'Department'},{name:'semester',label:'Semester',type:'number'},{name:'expires_at',label:'Expires at',type:'datetime-local'},{name:'content',label:'Notice',type:'textarea',required:true,span:true}]},
  { key:'events',label:'Events',singular:'Event',icon:PartyPopper,columns:[['title','Title'],['event_type','Type'],['start_at','Starts'],['end_at','Ends'],['venue','Venue']],fields:[{name:'title',label:'Title',required:true},{name:'event_type',label:'Type',type:'select',options:['event','holiday','workshop','seminar','placement']},{name:'start_at',label:'Start',type:'datetime-local',required:true},{name:'end_at',label:'End',type:'datetime-local',required:true},{name:'venue',label:'Venue'},{name:'department',label:'Department'},{name:'description',label:'Description',type:'textarea',span:true}]},
  { key:'study_materials',label:'Study materials',singular:'Study material',icon:BookOpen,columns:[['title','Title'],['subject','Subject'],['department','Department'],['semester','Sem.'],['material_type','Type']],fields:[{name:'title',label:'Title',required:true},{name:'subject',label:'Subject',required:true},...scope,{name:'material_type',label:'Type',type:'select',options:['document','video','link','notes']},{name:'file_url',label:'File URL',type:'url',required:true,span:true},{name:'description',label:'Description',type:'textarea',span:true}]},
  { key:'emergency_contacts',label:'Emergency',singular:'Emergency contact',icon:ShieldAlert,columns:[['name','Name'],['role','Role'],['phone','Phone'],['available_hours','Availability'],['priority','Priority']],fields:[{name:'name',label:'Name',required:true},{name:'role',label:'Role',required:true},{name:'phone',label:'Phone',required:true},{name:'email',label:'Email',type:'email'},{name:'available_hours',label:'Available hours'},{name:'priority',label:'Priority',type:'number'},{name:'active',label:'Active',type:'checkbox'}]},
  { key:'college_info',label:'College info',singular:'Information item',icon:Building2,columns:[['title','Title'],['key','Key'],['category','Category'],['content','Information']],fields:[{name:'title',label:'Title',required:true},{name:'key',label:'Unique key',required:true},{name:'category',label:'Category',required:true},{name:'content',label:'Information',type:'textarea',required:true,span:true}]},
];
