import type { ComponentType } from 'react';
import { Users, CalendarDays, ClipboardList, GraduationCap, UserRound, Megaphone, PartyPopper, ShieldAlert, Building2, ListChecks, CircleHelp } from 'lucide-react';

export type Field = { name: string; label: string; type?: string; required?: boolean; options?: string[]; span?: boolean; defaultChecked?: boolean };
export type ResourceConfig = { key: string; label: string; singular: string; icon: ComponentType<{ size?: number }>; columns: Array<[string,string]>; fields: Field[] };
const scope: Field[] = [{ name:'department',label:'Department',required:true },{ name:'semester',label:'Semester',type:'number',required:true }];

export const resources: ResourceConfig[] = [
  { key:'students',label:'Students',singular:'Student',icon:Users,columns:[['student_id','Student ID'],['full_name','Name'],['roll_number','Roll no.'],['department','Department'],['course','Course'],['semester','Sem.'],['whatsapp_number','WhatsApp'],['whatsapp_opt_in','WhatsApp consent'],['web_push_opt_in','Web Push consent'],['active','Active']],fields:[{name:'student_id',label:'Student ID',type:'number',required:true},{name:'full_name',label:'Full name',required:true},{name:'whatsapp_number',label:'WhatsApp number',required:true},{name:'roll_number',label:'Roll number',type:'number',required:true},{name:'department',label:'Department',required:true},{name:'course',label:'Course',required:true},{name:'semester',label:'Semester',type:'number',required:true},{name:'whatsapp_opt_in',label:'WhatsApp notifications consent',type:'checkbox',defaultChecked:false},{name:'web_push_opt_in',label:'Free Web Push consent',type:'checkbox',defaultChecked:false},{name:'active',label:'Active student',type:'checkbox',defaultChecked:true}]},
  { key:'timetables',label:'Timetable',singular:'Class',icon:CalendarDays,columns:[['day_of_week','Day'],['start_time','Start'],['end_time','End'],['subject','Subject'],['teacher','Teacher'],['batch_group','Batch / Group'],['is_recess','Recess']],fields:[{name:'day_of_week',label:'Day',type:'select',options:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],required:true},{name:'start_time',label:'Start time',type:'time',required:true},{name:'end_time',label:'End time',type:'time',required:true},{name:'subject',label:'Subject'},{name:'teacher',label:'Teacher'},{name:'batch_group',label:'Batch / Group'},{name:'is_recess',label:'Recess',type:'checkbox',defaultChecked:false}]},
  { key:'assignments',label:'Assignments',singular:'Assignment',icon:ClipboardList,columns:[['title','Title'],['subject','Subject'],['department','Department'],['semester','Sem.'],['due_at','Due']],fields:[{name:'title',label:'Title',required:true},{name:'subject',label:'Subject',required:true},...scope,{name:'due_at',label:'Due date & time',type:'datetime-local',required:true},{name:'description',label:'Instructions',type:'textarea',span:true}]},
  { key:'exams',label:'Exams',singular:'Exam',icon:GraduationCap,columns:[['title','Exam'],['subject','Subject'],['exam_date','Date'],['start_time','Start'],['end_time','End']],fields:[{name:'title',label:'Exam title',required:true},{name:'subject',label:'Subject',required:true},...scope,{name:'exam_date',label:'Date',type:'date',required:true},{name:'start_time',label:'Start time',type:'time',required:true},{name:'end_time',label:'End time',type:'time',required:true},{name:'instructions',label:'Instructions',type:'textarea',span:true}]},
  { key:'attendance',label:'Attendance',singular:'Attendance record',icon:ListChecks,columns:[['student_id','Student ID'],['subject','Subject'],['attendance_date','Date'],['status','Status']],fields:[{name:'student_id',label:'Student ID',type:'number',required:true},{name:'subject',label:'Subject',required:true},{name:'attendance_date',label:'Date',type:'date',required:true},{name:'status',label:'Status',type:'select',options:['present','absent','late','excused'],required:true}]},
  { key:'faculty',label:'Faculty',singular:'Faculty member',icon:UserRound,columns:[['full_name','Name'],['designation','Designation'],['department','Department'],['subjects','Subjects'],['email','Email'],['phone','Phone']],fields:[{name:'full_name',label:'Full name',required:true},{name:'designation',label:'Designation',required:true},{name:'department',label:'Department',required:true},{name:'subjects',label:'Subjects (comma separated)'},{name:'email',label:'Email',type:'email'},{name:'phone',label:'Phone'},{name:'office',label:'Office'},{name:'office_room',label:'Office room'},{name:'office_hours',label:'Office hours'},{name:'active',label:'Active',type:'checkbox'}]},
  { key:'notices',label:'Notices',singular:'Notice',icon:Megaphone,columns:[['title','Title'],['category','Category'],['priority','Priority'],['published_at','Published'],['expires_at','Expires']],fields:[{name:'title',label:'Title',required:true},{name:'category',label:'Category',type:'select',options:['general','academic','placement','internship','holiday','emergency'],required:true},{name:'priority',label:'Priority',type:'select',options:['low','normal','high','urgent']},{name:'department',label:'Department'},{name:'semester',label:'Semester',type:'number'},{name:'expires_at',label:'Expires at',type:'datetime-local'},{name:'content',label:'Notice',type:'textarea',required:true,span:true}]},
  { key:'events',label:'Events',singular:'Event',icon:PartyPopper,columns:[['title','Title'],['event_type','Type'],['start_at','Starts'],['end_at','Ends'],['venue','Venue']],fields:[{name:'title',label:'Title',required:true},{name:'event_type',label:'Type',type:'select',options:['event','holiday','workshop','seminar','placement']},{name:'start_at',label:'Start',type:'datetime-local',required:true},{name:'end_at',label:'End',type:'datetime-local',required:true},{name:'venue',label:'Venue'},{name:'department',label:'Department'},{name:'description',label:'Description',type:'textarea',span:true}]},
  { key:'emergency_contacts',label:'Emergency',singular:'Emergency contact',icon:ShieldAlert,columns:[['contact_name','Contact'],['contact_type','Type'],['role_or_service','Role or service'],['emergency_type','Emergency'],['phone_number','Phone'],['priority','Priority'],['active','Status']],fields:[{name:'contact_type',label:'Contact type',type:'select',options:['faculty','public_service'],required:true},{name:'contact_name',label:'Contact name',required:true},{name:'phone_number',label:'Phone number',type:'tel',required:true},{name:'role_or_service',label:'Role or service',required:true},{name:'emergency_type',label:'Emergency type',type:'select',options:['Anti-ragging emergency','Campus safety issue','Hostel emergency','Medical emergency','Women’s safety issue','Academic crisis','Examination emergency','Transport emergency','Other urgent situation'],required:true},{name:'description',label:'When to contact',type:'textarea',required:true,span:true},{name:'priority',label:'Priority',type:'number',required:true},{name:'active',label:'Active',type:'checkbox'}]},
  { key:'college_info',label:'College info',singular:'Information item',icon:Building2,columns:[['title','Title'],['category','Category'],['content','Information']],fields:[{name:'title',label:'Title',required:true},{name:'category',label:'Category',required:true},{name:'content',label:'Information',type:'textarea',required:true,span:true}]},
  { key:'faqs',label:'FAQs',singular:'FAQ',icon:CircleHelp,columns:[['question','Question'],['category','Category'],['answer','Answer']],fields:[{name:'question',label:'Question',required:true,span:true},{name:'answer',label:'Answer',type:'textarea',required:true,span:true},{name:'category',label:'Category',required:true}]},
];
