import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { Activity, AlertTriangle, Bell, ChevronLeft, ChevronRight, CircleHelp, LayoutDashboard, LogOut, Menu, MessageCircle, PhoneCall, Plus, Search, Send, Trash2, X, Pencil, Users, ClipboardList, GraduationCap, Radio, CheckCircle2, ShieldAlert } from 'lucide-react';
import toast from 'react-hot-toast';
import { api, session } from './lib/api';
import { resources, type Field, type ResourceConfig } from './lib/resources';
import type { ApiList, DashboardStats } from '../shared/types';
import type { EmergencyContact } from '../shared/types';

function Login() {
  const navigate = useNavigate();
  const [loading,setLoading]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);const data=new FormData(e.currentTarget);try{const result=await api<{token:string}>('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(data))});session.set(result.token);navigate('/');}catch(err){toast.error(err instanceof Error?err.message:'Login failed')}finally{setLoading(false)}}
  return <main className="login-page"><section className="login-brand"><div className="brand-mark"><MessageCircle size={26}/></div><div><strong>CampusMate</strong><span>College intelligence, connected</span></div><div className="login-quote"><p>One clear place to keep students informed, supported, and on schedule.</p><span>Admin Console</span></div></section><section className="login-panel"><form className="login-form" onSubmit={submit}><div className="mobile-logo"><MessageCircle/><b>CampusMate</b></div><p className="eyebrow">WELCOME BACK</p><h1>Sign in to your workspace</h1><p className="muted">Manage academic information and student communication.</p><label>Email address<input name="email" type="email" autoComplete="email" required placeholder="admin@college.edu"/></label><label>Password<input name="password" type="password" autoComplete="current-password" required placeholder="Enter your password"/></label><button className="primary full" disabled={loading}>{loading?'Signing in...':'Sign in'}</button><p className="secure-note">Secure administrator access</p></form></section></main>
}

function Shell({children}:{children:ReactNode}){
  const location=useLocation();const navigate=useNavigate();const [open,setOpen]=useState(false);
  const nav=[{to:'/',label:'Overview',icon:LayoutDashboard},{to:'/notifications',label:'Notifications',icon:Bell},...resources.map(r=>({to:`/manage/${r.key}`,label:r.label,icon:r.icon}))];
  return <div className="app-shell"><aside className={open?'open':''}><div className="sidebar-brand"><div className="brand-mark"><MessageCircle size={20}/></div><div><b>CampusMate</b><span>ADMIN</span></div><button className="icon mobile-close" onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(({to,label,icon:Icon})=><button key={to} className={(to==='/'?location.pathname===to:location.pathname.startsWith(to))?'active':''} onClick={()=>{navigate(to);setOpen(false)}}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="sidebar-foot"><div className="system-live"><i></i><div><b>Systems operational</b><span>WhatsApp & AI services</span></div></div><button onClick={()=>{session.clear();navigate('/login')}}><LogOut size={18}/>Sign out</button></div></aside><div className="main-area"><header><button className="icon menu" onClick={()=>setOpen(true)}><Menu/></button><div className="header-title"><span>Campus operations</span></div><div className="header-actions"><button className="icon" title="Help"><CircleHelp/></button><div className="avatar">CA</div></div></header><main className="content">{children}</main></div>{open&&<div className="scrim" onClick={()=>setOpen(false)}/>}</div>
}

function Dashboard(){
  const [data,setData]=useState<DashboardStats|null>(null);useEffect(()=>{api<DashboardStats>('/admin/dashboard').then(setData).catch(e=>toast.error(e.message))},[]);
  const stats=[['Registered students',data?.students??'—',Users,'Across active cohorts'],['Active assignments',data?.activeAssignments??'—',ClipboardList,'Awaiting submission'],['Upcoming exams',data?.upcomingExams??'—',GraduationCap,'From today onward'],['Message delivery',`${data?.deliveryRate??'—'}%`,Radio,'Last 1,000 messages'] ] as const;
  return <><div className="page-heading"><div><p className="eyebrow">OVERVIEW</p><h1>Good to see you.</h1><p>Here’s what is happening across your campus today.</p></div><button className="primary" onClick={()=>location.assign('/notifications')}><Send size={17}/>Send notification</button></div><div className="stat-grid">{stats.map(([label,value,Icon,note])=><article className="stat" key={label}><div className="stat-icon"><Icon/></div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></article>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h2>Recent communications</h2><p>Latest messages sent by your team</p></div><Activity size={20}/></div><div className="activity-list">{!data?<Skeleton/>:data.recentActivity.length?data.recentActivity.map((item)=><div className="activity" key={item.id}><div className="activity-icon"><MegaphoneIcon/></div><div><b>{item.title}</b><span>{item.status} · {formatValue(item.created_at)}</span></div><i className={item.status==='sent'?'success':''}></i></div>):<Empty compact text="No communications sent yet."/>}</div></section><section className="panel quick-panel"><div className="panel-head"><div><h2>Quick actions</h2><p>Common campus updates</p></div></div><div className="quick-grid">{resources.slice(0,6).map(r=><button key={r.key} onClick={()=>location.assign(`/manage/${r.key}`)}><r.icon/><span>Manage {r.label.toLowerCase()}</span><ChevronRight/></button>)}</div></section></div></>
}
function MegaphoneIcon(){return <Bell size={17}/>}
function Skeleton(){return <div className="skeleton-lines"><i/><i/><i/></div>}
function Empty({text,compact=false}:{text:string,compact?:boolean}){return <div className={`empty ${compact?'compact':''}`}><Search/><b>Nothing here yet</b><span>{text}</span></div>}
function formatValue(v:unknown){if(v===true)return 'Active';if(v===false)return 'Inactive';if(v===null||v===undefined||v==='')return '—';const s=String(v);if(/^\d{4}-\d{2}-\d{2}T/.test(s))return new Date(s).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});return s}

function ResourcePage(){
  const {resource:key}=useParams();const config=resources.find(r=>r.key===key);const [items,setItems]=useState<Record<string,unknown>[]>([]);const [count,setCount]=useState(0);const [page,setPage]=useState(1);const [search,setSearch]=useState('');const [loading,setLoading]=useState(true);const [editing,setEditing]=useState<Record<string,unknown>|null|undefined>(undefined);
  const load=()=>{if(!config)return;setLoading(true);api<ApiList>(`/admin/${config.key}?page=${page}&pageSize=15&search=${encodeURIComponent(search)}`).then(r=>{setItems(r.data);setCount(r.total)}).catch(e=>toast.error(e.message)).finally(()=>setLoading(false))};useEffect(load,[key,page,search,config]);
  if(!config)return <Navigate to="/"/>;
  const itemKey=(item:Record<string,unknown>)=>String(config?.key==='students'?item.student_id:item.id);
  async function remove(id:string){if(!confirm(`Delete this ${config!.singular.toLowerCase()}? This cannot be undone.`))return;try{await api(`/admin/${config!.key}/${encodeURIComponent(id)}`,{method:'DELETE'});toast.success('Deleted');load()}catch(e){toast.error(e instanceof Error?e.message:'Delete failed')}}
  return <><div className="page-heading"><div><p className="eyebrow">ACADEMIC DATA</p><h1>{config.label}</h1><p>{count} {count===1?config.singular.toLowerCase():config.label.toLowerCase()} in the system</p></div><button className="primary" onClick={()=>setEditing(null)}><Plus size={18}/>Add {config.singular.toLowerCase()}</button></div><section className="table-panel"><div className="table-tools"><div className="search"><Search/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder={`Search ${config.label.toLowerCase()}...`}/></div><span>{count} records</span></div><div className="table-wrap"><table><thead><tr>{config.columns.map(([,label])=><th key={label}>{label}</th>)}<th></th></tr></thead><tbody>{loading?<tr><td colSpan={config.columns.length+1}><Skeleton/></td></tr>:items.map(item=><tr key={itemKey(item)}>{config.columns.map(([field])=><td key={field}><span className={field==='active'?item[field]?'badge success':'badge muted':field==='priority'?`badge ${item[field]}`:''}>{formatValue(item[field])}</span></td>)}<td className="row-actions"><button className="icon" title="Edit" onClick={()=>setEditing(item)}><Pencil/></button><button className="icon danger" title="Delete" onClick={()=>remove(itemKey(item))}><Trash2/></button></td></tr>)}</tbody></table>{!loading&&!items.length&&<Empty text={`Add your first ${config.singular.toLowerCase()} to get started.`}/>}</div>{count>15&&<div className="pagination"><button className="icon" disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/></button><span>Page {page} of {Math.ceil(count/15)}</span><button className="icon" disabled={page>=Math.ceil(count/15)} onClick={()=>setPage(p=>p+1)}><ChevronRight/></button></div>}</section>{editing!==undefined&&<EditModal config={config} item={editing} close={()=>setEditing(undefined)} saved={()=>{setEditing(undefined);load()}}/>}</>
}

function EmergencyContactsPage(){
  const config=resources.find(resource=>resource.key==='emergency_contacts')!;
  const [contacts,setContacts]=useState<EmergencyContact[]>([]);
  const [loading,setLoading]=useState(true);
  const [editing,setEditing]=useState<Record<string,unknown>|null|undefined>(undefined);
  const load=()=>{setLoading(true);api<ApiList<EmergencyContact>>('/admin/emergency_contacts?page=1&pageSize=100&search=').then(result=>setContacts(result.data)).catch(error=>toast.error(error.message)).finally(()=>setLoading(false))};
  useEffect(load,[]);
  const groups=[
    {type:'public_service' as const,title:'Public emergency services',description:'Direct emergency and public safety numbers.'},
    {type:'faculty' as const,title:'College and faculty contacts',description:'College personnel assigned to serious student situations.'},
  ];
  async function remove(contact:EmergencyContact){if(!confirm(`Delete ${contact.contact_name}? This cannot be undone.`))return;try{await api(`/admin/emergency_contacts/${contact.id}`,{method:'DELETE'});toast.success('Emergency contact deleted');load()}catch(error){toast.error(error instanceof Error?error.message:'Delete failed')}}
  async function toggle(contact:EmergencyContact){try{await api(`/admin/emergency_contacts/${contact.id}`,{method:'PUT',body:JSON.stringify({...contact,active:!contact.active})});toast.success(contact.active?'Contact deactivated':'Contact activated');load()}catch(error){toast.error(error instanceof Error?error.message:'Update failed')}}
  return <><div className="page-heading"><div><p className="eyebrow">URGENT SUPPORT</p><h1>Emergency contacts</h1><p>{contacts.length} contacts configured for urgent situations</p></div><button className="primary" onClick={()=>setEditing(null)}><Plus/>Add emergency contact</button></div><div className="emergency-warning"><AlertTriangle/><div><b>For urgent or serious situations only</b><span>These contacts are intended for immediate safety, medical, campus, academic, or examination emergencies.</span></div></div>{loading?<section className="panel"><Skeleton/></section>:groups.map(group=>{const items=contacts.filter(contact=>contact.contact_type===group.type).sort((a,b)=>a.priority-b.priority);return <section className="emergency-section" key={group.type}><div className="emergency-section-head"><div><h2>{group.title}</h2><p>{group.description}</p></div><span>{items.length}</span></div>{items.length?<div className="emergency-grid">{items.map(contact=><article className={`emergency-contact ${contact.active?'':'inactive'}`} key={contact.id}><div className="emergency-contact-head"><div className="emergency-symbol"><ShieldAlert/></div><div><h3>{contact.contact_name}</h3><p>{contact.role_or_service}</p></div><span className={`badge ${contact.active?'success':'muted'}`}>{contact.active?'Active':'Inactive'}</span></div><div className="emergency-type">{contact.emergency_type}</div><p className="emergency-description">{contact.description}</p><div className="emergency-phone"><span>{contact.phone_number}</span><small>Priority {contact.priority}</small></div><div className="emergency-actions"><a className="call-now" href={`tel:${contact.phone_number.replace(/[^\d+]/g,'')}`}><PhoneCall/>Call now</a><button className="secondary" onClick={()=>toggle(contact)}>{contact.active?'Deactivate':'Activate'}</button><button className="icon" title="Edit" onClick={()=>setEditing(contact as unknown as Record<string,unknown>)}><Pencil/></button><button className="icon danger" title="Delete" onClick={()=>remove(contact)}><Trash2/></button></div></article>)}</div>:<div className="emergency-empty">No {group.title.toLowerCase()} configured.</div>}</section>})}{editing!==undefined&&<EditModal config={config} item={editing} close={()=>setEditing(undefined)} saved={()=>{setEditing(undefined);load()}}/>}</>
}

function EditModal({config,item,close,saved}:{config:ResourceConfig,item:Record<string,unknown>|null,close:()=>void,saved:()=>void}){
  const [busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const fd=new FormData(e.currentTarget);const body:object=Object.fromEntries(config.fields.map(f=>{let value:unknown=f.type==='checkbox'?fd.has(f.name):fd.get(f.name);if(f.type==='number'&&value!=='')value=Number(value);if(value==='')value=null;return[f.name,value]}));const id=item?String(config.key==='students'?item.student_id:item.id):'';try{await api(`/admin/${config.key}${item?`/${encodeURIComponent(id)}`:''}`,{method:item?'PUT':'POST',body:JSON.stringify(body)});toast.success(`${config.singular} ${item?'updated':'added'}`);saved()}catch(err){toast.error(err instanceof Error?err.message:'Could not save')}finally{setBusy(false)}}
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="modal"><div className="modal-head"><div><p className="eyebrow">{item?'EDIT':'NEW'}</p><h2>{item?`Edit ${config.singular.toLowerCase()}`:`Add ${config.singular.toLowerCase()}`}</h2></div><button className="icon" onClick={close}><X/></button></div><form onSubmit={submit}><div className="form-grid">{config.fields.map(field=><FormField key={field.name} field={field} value={item?.[field.name]}/>)}</div><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving...':'Save changes'}</button></div></form></section></div>
}
function FormField({field,value}:{field:Field,value:unknown}){let val=value??'';if(field.type==='datetime-local'&&val)val=String(val).slice(0,16);if(field.type==='time'&&val)val=String(val).slice(0,5);return <label className={`${field.span?'span':''} ${field.type==='checkbox'?'check':''}`}>{field.type==='checkbox'?<><input name={field.name} type="checkbox" defaultChecked={value===undefined?true:Boolean(value)}/><span>{field.label}</span></>:<><span>{field.label}{field.required&&<em>*</em>}</span>{field.type==='textarea'?<textarea name={field.name} defaultValue={String(val)} required={field.required}/>:field.type==='select'?<select name={field.name} defaultValue={String(val)} required={field.required}><option value="">Select</option>{field.options?.map(o=><option key={o}>{o}</option>)}</select>:<input name={field.name} type={field.type??'text'} defaultValue={String(val)} required={field.required}/>}</>}</label>}

function Notifications(){
  const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const raw=Object.fromEntries(new FormData(e.currentTarget));const payload={...raw,semester:raw.semester?Number(raw.semester):null,status:'draft'};try{const created=await api<{id:string}>('/admin/notifications',{method:'POST',body:JSON.stringify(payload)});await api(`/admin/notifications/${created.id}/send`,{method:'POST'});setSent(true);toast.success('Notification sent')}catch(err){toast.error(err instanceof Error?err.message:'Could not send')}finally{setBusy(false)}}
  return <><div className="page-heading"><div><p className="eyebrow">COMMUNICATIONS</p><h1>Send notification</h1><p>Broadcast clear, timely updates through WhatsApp.</p></div></div><div className="compose-layout"><form className="panel compose" onSubmit={submit}><div className="panel-head"><div><h2>Message details</h2><p>Keep it concise and action-oriented.</p></div></div>{sent?<div className="sent-state"><CheckCircle2/><h2>Message sent</h2><p>Your notification has been queued for delivery.</p><button type="button" className="secondary" onClick={()=>setSent(false)}>Compose another</button></div>:<><div className="form-grid"><label className="span"><span>Title <em>*</em></span><input name="title" required placeholder="e.g. Campus closed tomorrow"/></label><label className="span"><span>Message <em>*</em></span><textarea name="message" required maxLength={3500} placeholder="Write the update students should receive..."/></label><label><span>Category</span><select name="type"><option>notice</option><option>academic</option><option>emergency</option><option>event</option><option>reminder</option></select></label><label><span>Audience</span><select name="audience"><option value="all">All opted-in students</option><option value="segment">Class segment</option></select></label><label><span>Department (optional)</span><input name="department" placeholder="e.g. Computer Science"/></label><label><span>Semester (optional)</span><input name="semester" type="number" min="1" max="12"/></label></div><div className="modal-actions"><span className="muted">WhatsApp opt-in is always respected.</span><button className="primary" disabled={busy}><Send/>{busy?'Sending...':'Send now'}</button></div></>}</form><aside className="panel preview"><p className="eyebrow">WHATSAPP PREVIEW</p><div className="phone-preview"><div className="wa-head"><MessageCircle/><div><b>CampusMate</b><span>Official college assistant</span></div></div><div className="chat-bg"><div className="bubble"><b>Your notification title</b><p>Your message will appear here exactly as students receive it.</p><span>10:30 ✓✓</span></div></div></div><div className="delivery-note"><ShieldAlert/><div><b>Emergency updates</b><span>Use the emergency category only for urgent safety information.</span></div></div></aside></div></>
}

function Protected(){return session.get()?<Shell><Routes><Route index element={<Dashboard/>}/><Route path="manage/emergency_contacts" element={<EmergencyContactsPage/>}/><Route path="manage/:resource" element={<ResourcePage/>}/><Route path="notifications" element={<Notifications/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></Shell>:<Navigate to="/login"/>}
export default function App(){return <Routes><Route path="/login" element={session.get()?<Navigate to="/"/>:<Login/>}/><Route path="/*" element={<Protected/>}/></Routes>}
